# Generated by Django 3.2.7 on 2022-10-18 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Ссылка", "Ссылка"),
                            ("Заметка", "Заметка"),
                            ("Памятка", "Памятка"),
                            ("TODO", "TODO"),
                        ],
                        max_length=255,
                        verbose_name="Категория",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("header", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("content", models.TextField(blank=True, verbose_name="Текст")),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "favourite",
                    models.BooleanField(default=False, verbose_name="Избранное"),
                ),
                ("author", models.CharField(default="", max_length=255)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tags.category"
                    ),
                ),
            ],
            options={
                "verbose_name": "Заметки",
                "verbose_name_plural": "Заметки",
            },
        ),
    ]
