# Generated by Django 3.2.7 on 2022-10-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0002_alter_note_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="author",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
