# Generated by Django 3.2.7 on 2022-10-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_alter_note_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.CharField(choices=[('Ссылка', 'Ссылка'), ('Заметка', 'Заметка'), ('Памятка', 'Памятка'), ('TODO', 'TODO')], max_length=255),
        ),
    ]
