# Generated by Django 3.2.7 on 2022-10-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0006_alter_note_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='author',
            field=models.CharField(default='', max_length=255),
        ),
    ]
